### ISSUE TITLE
Build failed when checking out master

### ISSUE THREAD

**Issue by bneumann** [Xenoage/Zong#2]
Hi there,

I tried to build the gradle task "player" on the master branch but somehow it looks like a namespace is missing (maybe not checked in?) 

`:core:compileJavawarning: [options] bootstrap class path not set in conjunction with -source 1.6
D:\Projekte\Zong\core\src\com\xenoage\zong\Voc.java:3: error: package com.xenoage.utils.lang does not exist
import com.xenoage.utils.lang.VocID;`

**Comment by Xenoage** [comment]
Did you also clone the Xenoage Utils submodule? ( git submodule update )
See https://xenoage.atlassian.net/wiki/display/ZONG/Download

Am 27.12.2015 um 15:50 schrieb Benjamin Neumann:

**Comment by bneumann** [comment]
Sorry was missing that part. Works fine now
