### ISSUE TITLE
Can not apply into the Android Studio

### ISSUE THREAD

**Issue by d9x2knv7** [Xenoage/Zong#3]
Hi Xenoage
Can not run success when I put 'mobile-android' into the Android Studio.
![image](https://cloud.githubusercontent.com/assets/19966125/17129398/77362566-5345-11e6-8fcd-75fab0f67bb7.png)

Thank you,
Yu

**Comment by Xenoage** [comment]
Before we dive deeper into that issue, did you read this page https://xenoage.atlassian.net/wiki/display/ZONG/Using+Android+Studio ? Does it help?

**Comment by d9x2knv7** [comment]
Yes, you mean first apply all the file into the IntelliJ IDEA,
![image](https://cloud.githubusercontent.com/assets/19966125/17234720/fdd239aa-556d-11e6-8f29-7570cd6bf6ac.png)

Then put it  mobile-android into the Android Studio? But it stock in this point, never moved.

**Comment by d9x2knv7** [comment]
![image](https://cloud.githubusercontent.com/assets/19966125/17235178/5aefc802-5571-11e6-895d-0f72d3c6e6c8.png)
And it happen again.

**Comment by d9x2knv7** [comment]
Still not working at all... please help...
![image](https://cloud.githubusercontent.com/assets/19966125/17236693/4f03113c-557d-11e6-89ee-f00a0124fa38.png)

**Comment by Xenoage** [comment]
Using IntelliJ is not required. Just open Android Studio, import the Android project from your local copy of Zong! (subdirectory "mobile-android") and you are good to go.
I just tried it with a fresh install of Android Studio 2.1.2 and a fresh copy of the Zong! repository.
Can you describe in detail, what you are doing? Or should I create a screencast of what I am doing?

**Comment by d9x2knv7** [comment]
Yes, the first screenshot is import the mobile-android into the Android Studio. That simple, but I went wrong. I have done nothing...
![image](https://cloud.githubusercontent.com/assets/19966125/17354864/cb0daefe-597e-11e6-9c1f-36200faa42ea.png)
Can you send your version to me might be it will work.

**Comment by Xenoage** [comment]
You are using the folder ".../Desktop/mobile-android". But "mobile-android" must be a subfolder of your local Zong! repository. Checkout Zong! for example in ".../Desktop/Zong" and then import ".../Desktop/Zong/mobile-android".

**Comment by d9x2knv7** [comment]
Hi, it does not work at all. But I can see it push some step forward, but with same problem.

**Comment by Xenoage** [comment]
Please provide a screenshot of your directory structure. I'd like to see the repository with its subfolders, including the `mobile-android` subfolder and the contents of the `utils` subfolder.

**Comment by Xenoage** [comment]
This is how it looks on my machine:
![dirs](https://cloud.githubusercontent.com/assets/1911191/17355212/39a160d4-594f-11e6-874f-e3021bb51d0f.jpg)

**Comment by d9x2knv7** [comment]
I do not have the "lib" folder.
![image](https://cloud.githubusercontent.com/assets/19966125/17355301/1eba8d58-5982-11e6-9cd5-4acb5242e9dd.png)
and "utils" folder is empty.

**Comment by Xenoage** [comment]
https://xenoage.atlassian.net/wiki/display/ZONG/Download

**Comment by d9x2knv7** [comment]
but in the Github does not have the libs folder as well.

**Comment by Xenoage** [comment]
The lib folder is created by the build script.
But you need the submodule in the utils folder. Check the link above.

**Comment by Evil85** [comment]
after the git submodule init and git submodule update all errors disappeared.
