### ISSUE TITLE
Does Zong support guitar tab?

### ISSUE THREAD

**Issue by jason0539** [Xenoage/Zong#4]
Hi, Andreas
Is zong only support stave?
It seems has some problem when I use zong to draw a file contains guitar tab,notation is not right.
Is there a plan to support guitar tab?
thanks.

**Comment by Xenoage** [comment]
Zong! does not support guitar staves at the moment. We would like to add this feature later, but currently other issues have higher priority. If you are looking for more advanced open source music notation programs, have a look at musescore.org for example. MuseScore supports tablatures.
