### ISSUE TITLE
How to remove the "xml part" symbol?

### ISSUE THREAD

**Issue by ghost** [Xenoage/Zong#5]
Hi! I'm doing a project concerning musicxml files. Your project plays an important role in my data processing stage. Thanks a lot for your work!
By the way, I notice that there's always a "xml part " symbol in the output PDF in front of the staff. Could you do me a favor, tell me how to remove this symbol?
Thanks a lot!

**Comment by Xenoage** [comment]
If the text "xml part" is defined as a `<part-name>` in your MusicXML files, it is expected to be printed before the part. However I understand that you want to hide it. You can either remove the text from the file (provide an empty `<part-name></partname>`) or by calling
```
Part part = scoreDoc.getScore().getStavesList().getParts().get(0);
part.setName("");
```
