### ISSUE TITLE
easy way to hide or show instrument on the scource

### ISSUE THREAD

**Issue by Reaper10** [Xenoage/Zong#9]
Could Zong add an easy way to hide or show instrument on the score. I use MuseScore I can't seem to this option in MuseScore. It would love to see this option when the users print a score the instruments that are shown instruments are only ones painted.

**Comment by Xenoage** [comment]
In the source code, you can simply remove the staves you want to hide before rendering.
Of course, there is no GUI for it yet, since Zong! has no suitable GUI interface right now.
